//
// File generated by HDevelop for HALCON/.NET (C#) Version 17.12
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
using System.Windows;
using System.Windows.Controls;
using HalconDotNet;
using Heart.Inward;
using Heart.Outward;
/*注释
public partial class HDevelopExport
{
   public HTuple hv_ExpDefaultWinHandle;
   /*
   // Main procedure 
   private void action()
   {
       // Local iconic variables 

       HObject ho_Image1, ho_Image, ho_Rectangle;

       // Local control variables 

       HTuple hv_Row1 = null, hv_Column1 = null, hv_Row2 = null;
       HTuple hv_Column2 = null, hv_Mean = null, hv_Deviation = null;
       // Initialize local and output iconic variables 
       HOperatorSet.GenEmptyObj(out ho_Image1);
       HOperatorSet.GenEmptyObj(out ho_Image);
       HOperatorSet.GenEmptyObj(out ho_Rectangle);
       //读取图片，转换成灰度图片

       ho_Image1.Dispose();
       HOperatorSet.ReadImage(out ho_Image1, "C:/Users/Public/Documents/MVTec/HALCON-17.12-Progress/examples/images/cable1.png");
       ho_Image.Dispose();
       HOperatorSet.Rgb1ToGray(ho_Image1, out ho_Image);
       HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
       //选择测量的区域

       HOperatorSet.DrawRectangle1(hv_ExpDefaultWinHandle, out hv_Row1, out hv_Column1,
           out hv_Row2, out hv_Column2);
       ho_Rectangle.Dispose();
       HOperatorSet.GenRectangle1(out ho_Rectangle, hv_Row1, hv_Column1, hv_Row2, hv_Column2);

       //检测灰度
       HOperatorSet.Intensity(ho_Rectangle, ho_Image, out hv_Mean, out hv_Deviation);
       HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
       MessageBox.Show(hv_Mean.ToString());

       ho_Image1.Dispose();
       ho_Image.Dispose();
       ho_Rectangle.Dispose();

   }



   public void InitHalcon()
   {
       // Default settings used in HDevelop 
       HOperatorSet.SetSystem("width", 512);
       HOperatorSet.SetSystem("height", 512);
   }

   public void RunHalcon(HTuple Window)
   {
       hv_ExpDefaultWinHandle = Window;
       action();
   }*/
/*
public void GatherGray(HTuple Window, TextBlock txbGray)
    {
        hv_ExpDefaultWinHandle = Window;

        // Local iconic variables 

        HObject ho_Image1, ho_Image, ho_Rectangle;

        // Local control variables 

        HTuple hv_Row1 = null, hv_Column1 = null, hv_Row2 = null;
        HTuple hv_Column2 = null, hv_Mean = null, hv_Deviation = null;
        // Initialize local and output iconic variables 
        HOperatorSet.GenEmptyObj(out ho_Image1);
        HOperatorSet.GenEmptyObj(out ho_Image);
        HOperatorSet.GenEmptyObj(out ho_Rectangle);
        //读取图片，转换成灰度图片
       
        ho_Image1.Dispose();
        //HOperatorSet.ReadImage(out ho_Image1, "D:/Document And Settings3/123/Desktop/机器视觉记录/test photo/test4.jpg");
        ho_Image.Dispose();
        HOperatorSet.Rgb1ToGray(ho_Image1, out ho_Image);
        HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
        //选择测量的区域

        HOperatorSet.DrawRectangle1(hv_ExpDefaultWinHandle, out hv_Row1, out hv_Column1,
            out hv_Row2, out hv_Column2);
        ho_Rectangle.Dispose();
        HOperatorSet.GenRectangle1(out ho_Rectangle, hv_Row1, hv_Column1, hv_Row2, hv_Column2);

        //检测灰度
        HOperatorSet.Intensity(ho_Rectangle, ho_Image, out hv_Mean, out hv_Deviation);
        HOperatorSet.DispObj(ho_Image, hv_ExpDefaultWinHandle);
        //MessageBox.Show(hv_Mean.ToString());
        txbGray.Text = ((double)hv_Mean).ToString("0.00");

        //打印输出数据
        Console.WriteLine("OK，没问题的！");

        ho_Image1.Dispose();
        ho_Image.Dispose();
        ho_Rectangle.Dispose();
    }

}

    */